# Generated by Django 5.1.3 on 2025-01-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requiredcomponent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clientcomponent',
            name='component_id',
        ),
        migrations.RemoveField(
            model_name='requiredcomponent',
            name='component_id',
        ),
        migrations.DeleteModel(
            name='ComponentCategory',
        ),
    ]
