# Generated by Django 5.1.3 on 2025-01-17 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_remove_requiredcomponent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_given_tk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
