# Generated by Django 5.1.3 on 2025-01-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_project_customer_given_tk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcomponent',
            name='client_reference',
        ),
        migrations.RemoveField(
            model_name='clientcomponent',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='requiredcomponent',
            name='lead_time_days',
        ),
        migrations.RemoveField(
            model_name='requiredcomponent',
            name='specifications',
        ),
    ]
