# Generated by Django 4.2.7 on 2025-03-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliobackend', '0002_category_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('links', models.TextField()),
            ],
        ),
    ]
