# Generated by Django 5.1.3 on 2025-01-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_remove_person_birth_date_remove_person_death_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_children', to='genealogy.person'),
        ),
    ]
