# Generated by Django 5.1.3 on 2025-01-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0003_person_birth_date_person_father'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
