# Generated by Django 5.1.3 on 2025-01-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0004_alter_person_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_children', to='genealogy.person'),
        ),
    ]
