# Generated by Django 5.1.3 on 2025-01-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0006_alter_person_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
